Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/urls.py
from django.urls import path
from django.urls import path
from blog import views

app_name = 'blog'

# Views de postagem
urlpatterns = [
    path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='posts'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

]

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager 

# Crie seus modelos aqui.

# Criando nosso próprio gerenciador de modelos.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published') 

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Drafit'),
        ('published','Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=250,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager() # O gerenciado padrão
    published = PublishedManager() # O novo gerenciador que criamos

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                       self.publish.month,
                       self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, 
                             on_delete=CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comentado por {self.name} no {self.post}'

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/forms.py
from django import forms
from blog.models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body') 

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404
from django.core.paginator import  Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from blog.models import Post, Comment
from blog.forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

# Crie suas views aqui.
"""def post_list(request):
    
        Função para recebe apenas a requisão via path. Essa view é responsábel por mostrar todos os deados que tiverem com o status de published.
    
    posts = Post.published.all()
    return render(request, 'blog/post/list.html', {'posts':posts})"""

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # Três publicações por página
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Se a página não foi um número inteiro, exibir a primeira página
        posts = paginator.page(1)
    except EmptyPage:
        # Se a página estiver fora do intervalo, 
        # exibir a última página de resultados. 
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page':page, 
                                                   'posts':posts,
                                                   'tag':tag})

"""class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'"""

def post_detail(request, year, month, day, post):
    """
        View responsável por mostrar um dado de forma individual, uma postagem por vez.
        recebe por parâmetro os seguintes aspécitos via path, request, a própria requsição, o ano, o mês, e o dia, todos em valor inteior. Por fim a variável post. 
    """
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Lista dos comentários ativos para esta postagem
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # Um comentário foi postado
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Cria o objeto Comment, mas não o salva ainda no banco de dados
            new_comment = comment_form.save(commit=False)
            # Atribua a postagem atual ao comentário
            new_comment.post = post
            # Salva o comentário no banco de dados
            new_comment.save()
    else:
        comment_form = CommentForm()

    # lista de postagens Semeslhantes
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post':post,
                                                     'comments':comments,
                                                     'comment_form':comment_form,
                                                     'new_comment':new_comment,
                                                     'smilar_posts':similar_posts})

def post_share(request, post_id):
    # Obter a postagem com base no id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Formulário foi submetido
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Campos do formulário passaram pela validação
            cd = form.cleaned_data # Todos os dados no formato de dicionário
            post_url =  request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} Recomenda você ler {post.title}'
            message = f'Leia {post.title} at {post_url}\n\n {cd["name"]}\'s Comentários: {cd["comments"]}'
            send_mail(subject, message, 'desenvolvedorvaleriano@gmail.com', [cd['to']])
            sent=True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post':post, 
                                                    'form':form,
                                                    'sent':sent})
    

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Meu blog</h2>
        <p>Este é meu blog!</p>
    </div>
</body>
</html>

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Publicado {{ post.title }} por {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Compartilhar este Poste
        </a>
    </p>
    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Não há postes similares
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} Comentário{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p>
                Comentado {{ forloop.counter }} por {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Não há Comentários.</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Seu comentário foi adicionado com sucesso</h2>
    {% else %}
        <h2>Adiconar um novo comentário:</h2>
        <form method="POST">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Adicionar Comentário"></p>
        </form>
    {% endif %}
{% endblock %}

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Meu Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Postes com as Taggs {{ tag.name }}</h2>
    {% endif  %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
                <p class="tags">
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' 'tag_slug' %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            </a>
        </h2>
        <p class="date">
            Publicado {{ post.publish }} por {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}    

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block  title%}Compartilhar um Poste{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail Enviado com Sucesso</h1>
        <p>
            "{{ post.title }}" foi enviado com sucesso para "{{ form.cleaned_data.to }}"
        </p>
    {% else %}
        <h1>Compartilhar "{{ post.title }}" por e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Enviar E-mail">
        </form>
    {% endif %}
{% endblock %}

Livro - Aprenda Dajngo 3 com Exemplos/Capítulo 2/Blog/mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Anterior</a>
        {% endif %}
        <span class="current">
            Página {{ page.number }} de {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Próximo</a>
        {% endif %}
    </span>
</div>